name: weekly build

on:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  Weekly_Build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - qt_arch: win64_mingw
            qt_ver: 6.5.*
            qt_tools_mingw_install: mingw1120_64
            app_name: DataReport
    steps:
    # 拉取仓库
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    # 配置Git的username和email
    - uses: tidylabs/action-git-config-user@v1
    - name: Get Current Date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    # 创建tag
    - name: Git Describe Tag
      run: |
        git tag -d weekly
        git tag weekly -m "weekly build"
        git describe --tags
    # 创建changelog
    - name: Create changelog text
      id: changelog
      uses: mengyou1024/action-changelog@v0.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude_types: other,doc,chore
    # 安装ISCC
    - uses: Minionguyjpro/Inno-Setup-Action@v1.0.0
    # 安装Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_ver }}
        arch: ${{ matrix.qt_arch }}
        cache: ${{steps.cache-qt.outputs.cache-hit}}
        modules: 'qt5compat qtmultimedia qtshadertools qtimageformats'
    # 配置、编译程序
    - name: CMake Config
      run: cmake -B build -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}" -G "Ninja"  -DCMAKE_BUILD_TYPE=Release
    - name: CMake Build
      run: cmake --build build --target generate_exe_installer --config Release
    # 打包输出文件
    - name: Package 
      run: |
        pushd output
        mv dist ${{ matrix.app_name }}
        7z a -tZip ${{ matrix.app_name }}.zip ./${{ matrix.app_name }}/*
        cp ${{ matrix.app_name }}.zip ../${{ matrix.app_name }}.zip
        popd
    # 删除之前发布的版本
    - uses: dev-drprasad/delete-tag-and-release@v1.0 
      with:
        tag_name: weekly 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_release: true 
    # 更新发布release
    - name: Update Weekly Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: weekly
        name: 'Weekly Release $$'
        prerelease: true
        body: ${{ steps.changelog.outputs.changes }}
        files: |
          ./${{ matrix.app_name }}.zip
          ./output/install/${{ matrix.app_name }}Installer.exe
